### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by adriandobrica** [lucic71/dissertation-upb#2]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/backg.tex#L117 <- segmentation typo

**Comment by adriandobrica** [comment]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/intro.tex#L14 <- optimizations typo

**Comment by adriandobrica** [comment]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/intro.tex#L21 <- instead of "as discussed" I'd say "as mentioned (before)", because you've only mentioned (discussion is something more in depth than just indicating the term) the signed integer overflow. You're going to discuss it later on, in the background.

**Comment by adriandobrica** [comment]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/relwork.tex#L3

How do you plan to differ from this related work or build upon it? What are their drawbacks? I think that this section should end with a phrase where you try to address these questions. It doesn't have to be something long - what I noticed is that this section needs to be somehow connected to the rest of the report.

"These are the drawbacks of the related work/these are the parts that can be improved/there is not enough related work" -> and after this, the next section where you show your research plan will feel more connected to the report.

**Comment by adriandobrica** [comment]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/contr.tex#L17

Might be useful to say/estimate what kind of HW specifications you are going to need? Not sure if it deserves to be included or not, but I thought it's worth it to mention it here, if you think it would be useful for you.

**Comment by adriandobrica** [comment]
https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/concl.tex#L4

Try to "link" your chapters the way you are doing it in the conclusion. (Throwback to related work and research plan)

**Comment by adriandobrica** [comment]
@lucic71

**Comment by lucic71** [comment]
> https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/concl.tex#L4
> 
> Try to "link" your chapters the way you are doing it in the conclusion. (Throwback to related work and research plan)

**Comment by lucic71** [comment]
> https://github.com/lucic71/dissertation-upb/blob/b391772c8c5daf095e9dd7caf29da1627c9adad3/r1/concl.tex#L4
> 
> Try to "link" your chapters the way you are doing it in the conclusion. (Throwback to related work and research plan)

I don't quite understand this. Do you mean to explicitly throwback to specific sections (with phrases "as discussed in section x")?  I tried in some way or another to allocate a sentence for the main idea of each section.

**Comment by adriandobrica** [comment]
As a rule of thumb, make sure that when you read the ending of a chapter and the beginning of the following one, they feel connected. This was my suggestion from above.

**Comment by lucic71** [comment]
I will close this issue as tonight is the submission deadline and I covered all your feedback, thanks!
